baseURL = "http://example.org/"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
title = "é‚£é‚£é‚£å‘€"
theme = "zozo"
hasCJKLanguage = true                  # has chinese/japanese/korean ?  # è‡ªåŠ¨æ£€æµ‹æ˜¯å¦åŒ…å« ä¸­æ–‡\æ—¥æ–‡\éŸ©æ–‡
summaryLength = 100
paginate = 5                           # shows the number of articles  # é¦–é¡µæ˜¾ç¤ºæ–‡ç« æ•°é‡
enableEmoji = true
googleAnalytics = ""                   # your google analytics id
disqusShortname = ""                   # your discuss shortname

pygmentsUseClasses = true
pygmentCodeFences = true
pygmentscodefencesguesssyntax = true

[author]
  name = "wangcch"

[[menu.main]]
  name = "Archive"
  weight = 20
  identifier = "archive"
  url = "/posts/"
[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"

[params]
  subTitle = "ä¸€ä¸ªå°ä¼™"                                       # site's subTitle  # ç½‘ç«™äºŒçº§æ ‡é¢˜
  footerSlogan = ""                                   # site's footer slogan  # ç½‘ç«™é¡µè„šæ ‡è¯­
  keywords = ["Dave","wangcch","blog", "wangcch.cc", "é‚£å¹´è½½ä½ çš„åˆå¤", "é‚£é‚£é‚£é‚£é‚£å‘€", "é‚£é‚£é‚£å‘€"]
  description = "wangcch's blog. you're the starâœ¨. One ğŸ´ğŸ‘¨â€ğŸ³ 's struggle journey. O_O"
  enableMathJax = true                                                 # enable mathjax  # æ˜¯å¦ä½¿ç”¨mathjaxï¼ˆæ•°å­¦å…¬å¼ï¼‰
  enableSummary = true                                                 # display the article summary  # æ˜¯å¦æ˜¾ç¤ºæ–‡ç« æ‘˜è¦
  mainSections = ["posts"]

[params.disqus]
  enable = true
  shortname = "blog-natzanfkii"

[social]
  github = "https://github.com/wangcch"
  twitter = "https://twitter.com/_wangcch"
  weibo = "https://weibo.com/wangcch"
